### ISSUE TITLE
sidebar settings

### ISSUE THREAD

**Issue by khayargoli** [SidebarJS/angular-sidebarjs#4]
Is there a way to disable sliding the menu when we try to drag from left side of the mobile screen?

**Comment by lorenzodianni** [comment]
Yes, you can prevent swipe open with the option `nativeSwipeOpen: false`

```html
<sidebarjs sidebarjs-config="{nativeSwipeOpen: false}">
  <h1>Angular SidebarJS</h1>
</sidebarjs>
```

Check all [configuration options](https://github.com/SidebarJS/sidebarjs#options)
___

`<sidebarjs />` has also some binding functions:
```html
<sidebarjs
  on-close="app.onSidebarClose()"
  on-open="app.onSidebarOpen()"
  on-change-visibility="app.onSidebarChangeVisibility($event)">
  <h1>Angular SidebarJS</h1>
</sidebarjs>
```
___

I'll improve documentations as soon as possible 👍
