### ISSUE TITLE
Sidebar not closing on button click

### ISSUE THREAD

**Issue by vikeie** [SidebarJS/angular-sidebarjs#5]
I have given  my code of sidebar directive below.

in my template:
`<sidebarjs on-change-visibility="close_class == 'close'">
      <div class="sidebar-head">Find User</div>
      <nav>
        <ul class="sidebar-menu">
          <li ng-repeat="radius in radius"><a
         href="#" ui-sref="users({radius_id: $state.params.radius_id})" ui-sref-opts="{reload: true}">radius.name</a></li>
        </ul>
      </nav>
    </sidebarjs>`

in my app.js:
`var home = angular.module('wm.home',[uiRouter,'angular-carousel','ngSidebarJS'])`

When I click on an option among the list, sidebar doesn't close and the required page loads behind. sidebar closes only when I click on the toggle button or outside the sidebar.. Anyone kindly help me to close the sidebar onclick of any of the options in the list.

**Comment by lorenzodianni** [comment]
Hi @vikeie, a working [example](https://stackblitz.com/edit/angularjs-jf6ahv)

**Comment by 120dev** [comment]
hello your example is no longer online is it possible to put it back? thank you

**Comment by lorenzodianni** [comment]
Hi @120dev 
A new example is available on [stackblitz](https://stackblitz.com/edit/angular-sidebarjs) 🎉
